package com.example.demo.service;
import com.example.demo.dto.*; import com.example.demo.entity.*; import com.example.demo.exception.ApiException; import com.example.demo.repository.InMemorySalesRepository; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import java.time.LocalDateTime; import java.util.*;
@Service
public class SalesService {
    private final InMemorySalesRepository repo; public SalesService(InMemorySalesRepository repo){this.repo=repo;}
    public void adminOnly(String auth){admin(auth);}
    public AuthResponse register(AuthRequest r){required(r.email(),"Email là bắt buộc");required(r.password(),"Mật khẩu là bắt buộc");String email=r.email().toLowerCase();if(repo.users.containsKey(email))throw bad("Email đã được sử dụng");repo.users.put(email,new User(blank(r.name(),"Khách hàng"),email,r.phone(),r.password(),"CUSTOMER",true));return login(r);}
    public AuthResponse login(AuthRequest r){User u=repo.users.get(r.email()==null?"":r.email().toLowerCase());if(u==null||!Objects.equals(u.password,r.password())||!u.active)throw new ApiException(HttpStatus.UNAUTHORIZED,"Email, mật khẩu hoặc trạng thái tài khoản không hợp lệ");String token=UUID.randomUUID().toString();repo.tokens.put(token,u.email);return new AuthResponse(token,u.publicView());}
    public void resetPassword(ForgotPasswordRequest r){required(r.email(),"Email là bắt buộc");required(r.newPassword(),"Mật khẩu mới là bắt buộc");User u=repo.users.get(r.email().toLowerCase());if(u==null)throw notFound();u.password=r.newPassword();}
    public Map<String,Object> profile(String auth){return user(auth).publicView();}
    public Map<String,Object> updateProfile(String auth,ProfileRequest r){User u=user(auth);required(r.name(),"Họ tên là bắt buộc");u.name=r.name();u.phone=r.phone();return u.publicView();}
    public void changePassword(String auth,ChangePasswordRequest r){User u=user(auth);required(r.newPassword(),"Mật khẩu mới là bắt buộc");if(!Objects.equals(u.password,r.currentPassword()))throw bad("Mật khẩu hiện tại không đúng");u.password=r.newPassword();}
    public List<Product> products(String search,String category){return repo.products.values().stream().filter(p->p.active).filter(p->search==null||p.name.toLowerCase().contains(search.toLowerCase())).filter(p->category==null||category.isBlank()||p.category.equalsIgnoreCase(category)).sorted(Comparator.comparing(p->p.id)).toList();}
    public Product product(long id){return findProduct(id);} public List<String> categories(){return repo.products.values().stream().map(p->p.category).distinct().sorted().toList();}
    public Product create(String auth,ProductRequest r){admin(auth);required(r.category(),"Danh mục là bắt buộc");repo.categories.add(r.category());Product p=new Product(repo.productSequence.getAndIncrement(),r.name(),r.category(),r.price(),r.stock(),r.active(),r.description(),r.imageUrl());repo.products.put(p.id,p);return p;}
    public Product update(String auth,long id,ProductRequest r){admin(auth);required(r.category(),"Danh mục là bắt buộc");repo.categories.add(r.category());Product p=findProduct(id);p.name=r.name();p.category=r.category();p.price=r.price();p.stock=r.stock();p.active=r.active();p.description=r.description();p.imageUrl=r.imageUrl();return p;}
    public List<String> adminCategories(String auth){admin(auth);return repo.categories.stream().sorted().toList();}
    public List<String> createCategory(String auth,CategoryRequest r){admin(auth);required(r.name(),"Tên danh mục là bắt buộc");repo.categories.add(r.name());return adminCategories(auth);}
    public List<String> renameCategory(String auth,String oldName,CategoryRequest r){admin(auth);required(r.name(),"Tên danh mục là bắt buộc");if(!repo.categories.remove(oldName))throw notFound();repo.categories.add(r.name());repo.products.values().stream().filter(p->p.category.equalsIgnoreCase(oldName)).forEach(p->p.category=r.name());return adminCategories(auth);}
    public void deleteCategory(String auth,String name){admin(auth);if(repo.products.values().stream().anyMatch(p->p.category.equalsIgnoreCase(name)))throw bad("Không thể xóa danh mục đang có sản phẩm");if(!repo.categories.remove(name))throw notFound();}
    public void delete(String auth,long id){admin(auth);repo.products.remove(id);}
    public List<CartItemResponse> cart(String auth){return cartFor(user(auth)).stream().map(this::cartResponse).toList();}
    public List<CartItemResponse> addCart(String auth,CartRequest r){User u=user(auth);Product p=findProduct(r.productId());int quantity=Math.max(1,r.quantity());if(p.stock<quantity)throw bad("Số lượng vượt quá tồn kho");List<CartItem> cart=cartFor(u);CartItem item=cart.stream().filter(i->i.productId==p.id).findFirst().orElse(null);if(item==null)cart.add(new CartItem(p.id,quantity));else{if(item.quantity+quantity>p.stock)throw bad("Số lượng vượt quá tồn kho");item.quantity+=quantity;}return cart.stream().map(this::cartResponse).toList();}
    public List<CartItemResponse> updateCart(String auth,long productId,CartRequest r){List<CartItem> cart=cartFor(user(auth));CartItem item=cart.stream().filter(i->i.productId==productId).findFirst().orElseThrow(()->bad("Không có sản phẩm trong giỏ"));if(r.quantity()<=0)cart.remove(item);else{Product p=findProduct(productId);if(r.quantity()>p.stock)throw bad("Số lượng vượt quá tồn kho");item.quantity=r.quantity();}return cart.stream().map(this::cartResponse).toList();}
    public void removeCart(String auth,long productId){cartFor(user(auth)).removeIf(i->i.productId==productId);}
    public Order checkout(String auth,CheckoutRequest r){User u=user(auth);List<CartItem> cart=cartFor(u);if(cart.isEmpty())throw bad("Giỏ hàng đang trống");required(r.address(),"Địa chỉ nhận hàng là bắt buộc");List<OrderItem> lines=new ArrayList<>();double total=0;for(CartItem c:cart){Product p=findProduct(c.productId);if(p.stock<c.quantity)throw bad("Sản phẩm "+p.name+" không đủ tồn kho");p.stock-=c.quantity;lines.add(new OrderItem(p.name,c.quantity,p.price));total+=c.quantity*p.price;}Order order=new Order(repo.orderSequence.getAndIncrement(),u.email,r.receiver(),r.phone(),r.address(),r.note(),r.paymentMethod(),"PENDING",total,LocalDateTime.now(),lines);repo.orders.put(order.id,order);cart.clear();return order;}
    public List<Order> orders(String auth){User u=user(auth);return repo.orders.values().stream().filter(o->u.role.equals("ADMIN")||o.email.equals(u.email)).sorted(Comparator.comparing((Order o)->o.createdAt).reversed()).toList();}
    public Order changeOrder(String auth,long id,StatusRequest r){admin(auth);Order o=repo.orders.get(id);if(o==null)throw notFound();o.status=r.status();return o;}
    public Order cancelOrder(String auth,long id){User u=user(auth);Order o=repo.orders.get(id);if(o==null)throw notFound();if(!u.role.equals("ADMIN")&&!o.email.equals(u.email))throw new ApiException(HttpStatus.FORBIDDEN,"Không có quyền hủy đơn này");if(!"PENDING".equals(o.status))throw bad("Chỉ có thể hủy đơn đang chờ xác nhận");o.status="CANCELLED";return o;}
    public List<Map<String,Object>> users(String auth){admin(auth);return repo.users.values().stream().map(User::publicView).toList();}
    public Map<String,Object> changeUser(String auth,String email,StatusRequest r){admin(auth);User u=repo.users.get(email);if(u==null)throw notFound();u.active="ACTIVE".equalsIgnoreCase(r.status());return u.publicView();}
    public Map<String,Object> dashboard(String auth){admin(auth);double revenue=repo.orders.values().stream().filter(o->!"CANCELLED".equals(o.status)).mapToDouble(o->o.total).sum();Map<String,Long> statusCounts=repo.orders.values().stream().collect(java.util.stream.Collectors.groupingBy(Order::getStatus,java.util.stream.Collectors.counting()));Map<String,Long> categoryCounts=repo.products.values().stream().collect(java.util.stream.Collectors.groupingBy(Product::getCategory,java.util.stream.Collectors.counting()));Map<String,Object> res=new HashMap<>();res.put("revenue",revenue);res.put("orderCount",repo.orders.size());res.put("customerCount",repo.users.values().stream().filter(u->u.role.equals("CUSTOMER")).count());res.put("lowStock",repo.products.values().stream().filter(p->p.stock<10).count());res.put("statusCounts",statusCounts);res.put("categoryCounts",categoryCounts);res.put("recentOrders",repo.orders.values().stream().sorted(Comparator.comparing((Order o)->o.createdAt).reversed()).limit(5).toList());return res;}
    private Product findProduct(long id){Product p=repo.products.get(id);if(p==null)throw notFound();return p;} private List<CartItem> cartFor(User u){return repo.carts.computeIfAbsent(u.email,k->new ArrayList<>());} private CartItemResponse cartResponse(CartItem i){Product p=findProduct(i.productId);return new CartItemResponse(p.id,p.name,p.category,p.price,i.quantity,p.price*i.quantity);} private User user(String auth){String token=auth==null?null:auth.replace("Bearer ","");String email=repo.tokens.get(token);if(email==null)throw new ApiException(HttpStatus.UNAUTHORIZED,"Vui lòng đăng nhập");return repo.users.get(email);} private void admin(String auth){if(!"ADMIN".equals(user(auth).role))throw new ApiException(HttpStatus.FORBIDDEN,"Chỉ quản trị viên được phép thực hiện");} private static void required(String value,String message){if(value==null||value.isBlank())throw bad(message);} private static String blank(String value,String fallback){return value==null||value.isBlank()?fallback:value;} private static ApiException bad(String message){return new ApiException(HttpStatus.BAD_REQUEST,message);} private static ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy dữ liệu");}
}
